### ISSUE TITLE
How to plot the periodicity-weight figure in the paper?

### ISSUE THREAD

**Issue by LanZhenFeng** [songjiang0909/DeepFS#1]
Thanks for sharing. I have some questions about how to plot the periodicity-weight figure in the paper? 
Do you use weights(weights_pred) of the output? Or something else?
If it is weights, how to deal with it to plot the figure in the paper? after all, there are negative values in weights.
At last, can you provide the code to draw this figure if possible?

**Comment by songjiang0909** [comment]
Hi @LanZhenFeng,

Since sinusoidal function is used to denote periodicity, the positive/negative weights don't matter (it only causes a shift in phase). Therefore we can just use the absolute value of weights.

The "plot" code simply uses ```matplotlib.pyplot.bar```
